name: Flutter CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_android:
    runs-on: ubuntu-latest
    env:
      API_KEY_WEB: AIzaSyB_g3IUod_fTYtWeOnu_lSE-V81cn8GV5w
      APP_ID_WEB: 1:613558748519:web:fe915e85b5a3d228dc9bc2
      MESSAGING_SENDER_ID: 613558748519
      PROJECT_ID: lawol-e2e60
      AUTH_DOMAIN: lawol-e2e60.firebaseapp.com
      STORAGE_BUCKET: lawol-e2e60.firebasestorage.app
      API_KEY_ANDROID: AIzaSyCqETRguwdAo1HAOW9NCdm9YXX0wrrOC9g
      APP_ID_ANDROID: 1:613558748519:android:fe915e85b5a3d228dc9bc2
      API_KEY_IOS: AIzaSyB_g3IUod_fTYtWeOnu_lSE-V81cn8GV5w
      APP_ID_IOS: 1:613558748519:ios:fe915e85b5a3d228dc9bc2
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter pub get
    - run: flutter pub run build_runner build
    - run: flutter clean
    - run: flutter build apk --release
    - uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk

  build_web:
    runs-on: ubuntu-latest
    env:
      API_KEY_WEB: AIzaSyB_g3IUod_fTYtWeOnu_lSE-V81cn8GV5w
      APP_ID_WEB: 1:613558748519:web:fe915e85b5a3d228dc9bc2
      MESSAGING_SENDER_ID: 613558748519
      PROJECT_ID: lawol-e2e60
      AUTH_DOMAIN: lawol-e2e60.firebaseapp.com
      STORAGE_BUCKET: lawol-e2e60.firebasestorage.app
      API_KEY_ANDROID: AIzaSyCqETRguwdAo1HAOW9NCdm9YXX0wrrOC9g
      APP_ID_ANDROID: 1:613558748519:android:fe915e85b5a3d228dc9bc2
      API_KEY_IOS: AIzaSyB_g3IUod_fTYtWeOnu_lSE-V81cn8GV5w
      APP_ID_IOS: 1:613558748519:ios:fe915e85b5a3d228dc9bc2
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter pub get
    - run: flutter pub run build_runner build
    - run: flutter clean
    - run: flutter build web --release
    - uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/develop'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web

  build_ios:
    runs-on: macos-latest
    env:
      API_KEY_WEB: AIzaSyB_g3IUod_fTYtWeOnu_lSE-V81cn8GV5w
      APP_ID_WEB: 1:613558748519:web:fe915e85b5a3d228dc9bc2
      MESSAGING_SENDER_ID: 613558748519
      PROJECT_ID: lawol-e2e60
      AUTH_DOMAIN: lawol-e2e60.firebaseapp.com
      STORAGE_BUCKET: lawol-e2e60.firebasestorage.app
      API_KEY_ANDROID: AIzaSyCqETRguwdAo1HAOW9NCdm9YXX0wrrOC9g
      APP_ID_ANDROID: 1:613558748519:android:fe915e85b5a3d228dc9bc2
      API_KEY_IOS: AIzaSyB_g3IUod_fTYtWeOnu_lSE-V81cn8GV5w
      APP_ID_IOS: 1:613558748519:ios:fe915e85b5a3d228dc9bc2
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter pub get
    - run: cd ios && pod repo update
    - run: rm ios/Podfile.lock
    - run: flutter pub run build_runner build
    - run: flutter clean
    - run: flutter build ipa --release --no-codesign
    - uses: actions/upload-artifact@v4
      with:
        name: ios-ipa
        path: build/ios/ipa/Runner.ipa
